"""empty message

Revision ID: 1926831a3595
Revises: 
Create Date: 2022-07-26 23:41:25.225998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1926831a3595'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.Column('employee_address', sa.String(length=100), nullable=False),
    sa.Column('employee_age', sa.Integer(), nullable=False),
    sa.Column('employee_description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
